### ISSUE TITLE
How to get keycloak ID in JAX-RS?

### ISSUE THREAD

**Issue by cdietze** [ahus1/keycloak-dropwizard-integration#21]
Hi there,

I need to get more information from Keycloak from within a JAX-RS method. Thus, I need the user's keycloak ID.
I can inject the current `de.ahus1.keycloak.dropwizard.User` via the `@Auth` annotation, however the ID is not accessible from that instance. Nor via a injected Principal or SecurityContext.

My current workaround is to have a custom user class:
```
public class KeycloakUserPrincipal extends AbstractUser {
...
/** Gets the users keycloak ID */
    public String getId() {
        AccessToken token = securityContext.getToken();
        if (token != null) {
            return token.getSubject();
        }
        return null;
    }
...
```

Is there a simpler way to get the users ID?
Or can we add such a method to the default `User`?

**Comment by ahus1** [comment]
The provided User class is meant to be minimal. Using a custom user class is the intended way to use it. 

There is currently only a bit of JavaDoc in _KeycloakBundle_ that describes it, I'll update the doc.

I read that you have extended AbstractUser. Reading your posting I am not sure if you performed all three steps stated below: after you have followed them, you will be able to inject your KeycloakUserPrincipal using the `@Auth` annotation. 

Please comment if this works for you.

----
(excerpt from the new doc I am about to write)

Optionally (if you want to use a different class instead of _User_ to wrap access to Keycloak):

1 override _getUserClass()_ to return the class you are using
1 override _createAuthenticator()_ to provide a factory to create the instances of your user class
1 override _createAuthorizer()_ to implement the role checking used by the _RolesAllowed_ annotation.

See the default implementations _User_, _UserAuthorizer_, and _KeycloakAuthenticator_ as a guide.

**Comment by cdietze** [comment]
Yes, I have it working with my custom User implementation.

Another idea is to make `User.getName` return the keycloak ID.
Which is also what `org.keycloak.KeycloakPrincipal` does.
I assume this ID is generally more useful than the users real name.

Another idea is to expose the `KeycloakSecurityContext` from the `User`. This would be less minimal but more useful :)

Either change would save having to implement 3 classes and taking the above steps. I assume it's a common thing to need the keycloak ID to get more info about the current user or to use that ID as a Key.

**Comment by ahus1** [comment]
The User class (or any class you write to replace it) is intended to wrap the Keycloak API. If the library would expose KeycloakSecurityContext, the Keycloak API will be all over your code wherever you inject and use the User object. And if the library would start to expose the properties, I wouldn't know where to stop.

Therefore I'll keep it "as is" for now. I've updated the docs to explain to users how to use it, I hope that will suffice.
